package com.fredy.mysavings.Util

import android.graphics.Color
import androidx.compose.material3.MaterialTheme
import co.yml.charts.common.model.Point
import androidx.compose.ui.graphics.Color as toColor

val TAG = "BABI"
val WebClientId = "895326687881-e2kh5jh12kjvpf9se1cehbeias0iuvmq.apps.googleusercontent.com"

val defaultColors = listOf(
    toColor(Color.parseColor("#fff300")),
    toColor(Color.parseColor("#f49a00")),
    toColor(Color.parseColor("#ff4d00")),
    toColor(Color.parseColor("#ff0052")),
    toColor(Color.parseColor("#ff00f3")),
    toColor(Color.parseColor("#cc00c3")),
    toColor(Color.parseColor("#aa00e9")),
    toColor(Color.parseColor("#5400ff")),
    toColor(Color.parseColor("#0001ff")),
    toColor(Color.parseColor("#0039ff")),
    toColor(Color.parseColor("#0069ff")),
    toColor(Color.parseColor("#0098ff")),
    toColor(Color.parseColor("#00c6ff")),
    toColor(Color.parseColor("#00fffb")),
    toColor(Color.parseColor("#00ff1f")),
)


val currencyCodes = listOf(
    "AED",
    "AFN",
    "ALL",
    "AMD",
    "ANG",
    "AOA",
    "ARS",
    "AUD",
    "AWG",
    "AZN",
    "BAM",
    "BBD",
    "BDT",
    "BGN",
    "BHD",
    "BIF",
    "BMD",
    "BND",
    "BOB",
    "BRL",
    "BSD",
    "BTC",
    "BTN",
    "BWP",
    "BYN",
    "BYR",
    "BZD",
    "CAD",
    "CDF",
    "CHF",
    "CLF",
    "CLP",
    "CNY",
    "COP",
    "CRC",
    "CUC",
    "CUP",
    "CVE",
    "CZK",
    "DJF",
    "DKK",
    "DOP",
    "DZD",
    "EGP",
    "ERN",
    "ETB",
    "EUR",
    "FJD",
    "FKP",
    "GBP",
    "GEL",
    "GGP",
    "GHS",
    "GIP",
    "GMD",
    "GNF",
    "GTQ",
    "GYD",
    "HKD",
    "HNL",
    "HRK",
    "HTG",
    "HUF",
    "IDR",
    "ILS",
    "IMP",
    "INR",
    "IQD",
    "IRR",
    "ISK",
    "JEP",
    "JMD",
    "JOD",
    "JPY",
    "KES",
    "KGS",
    "KHR",
    "KMF",
    "KPW",
    "KRW",
    "KWD",
    "KYD",
    "KZT",
    "LAK",
    "LBP",
    "LKR",
    "LRD",
    "LSL",
    "LTL",
    "LVL",
    "LYD",
    "MAD",
    "MDL",
    "MGA",
    "MKD",
    "MMK",
    "MNT",
    "MOP",
    "MRO",
    "MUR",
    "MVR",
    "MWK",
    "MXN",
    "MYR",
    "MZN",
    "NAD",
    "NGN",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "OMR",
    "PAB",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RSD",
    "RUB",
    "RWF",
    "SAR",
    "SBD",
    "SCR",
    "SDG",
    "SEK",
    "SGD",
    "SHP",
    "SLE",
    "SLL",
    "SOS",
    "SRD",
    "STD",
    "SYP",
    "SZL",
    "THB",
    "TJS",
    "TMT",
    "TND",
    "TOP",
    "TRY",
    "TTD",
    "TWD",
    "TZS",
    "UAH",
    "UGX",
    "USD",
    "UYU",
    "UZS",
    "VEF",
    "VES",
    "VND",
    "VUV",
    "WST",
    "XAF",
    "XAG",
    "XAU",
    "XCD",
    "XDR",
    "XOF",
    "XPF",
    "YER",
    "ZAR",
    "ZMK",
    "ZMW",
    "ZWL"
)

data class ActionWithName(
    val name: String, val action: () -> Unit
)

data class ValueWithName<T>(
    val name: String, val value: T
)

data class ToggleableInfo(
    val isChecked: Boolean, val text: String
)

fun <T,U> listConverter(
    items: List<T>, convertFunction: (T) -> U
): List<U> {
    return items.map { item ->
        convertFunction(item)
    }
}

